GET https://sokker.org/api/player?filter[team]=111773&filter[limit]=200&filter[offset]=0

###
GET https://sokker.org/api/junior?filter[limit]=200&filter[offset]=0

###
GET https://sokker.org/api/training/players

###
GET https://sokker.org/api/player/38608010

###
GET https://sokker.org/api/current

###
POST https://sokker.org/api/auth/login
Content-Type: application/json

{
    "login": "choke",
    "password": "W3arethefantastics4.",
    "remember": true
}

###
GET https://sokker.org/api/match?filter[team]=111773&filter[season]=36&filter[limit]=200


###
POST https://light-loafers-deer.cyclic.app/api/:names/:123
Content-Type: application/json

{
    "name1": "choke",
    "name2": "choke2",
    "remember": true
}

###
GET https://light-loafers-deer.cyclic.app/:names/:123

###
GET http://localhost:3000/api/:pepe1

###
DELETE https://light-loafers-deer.cyclic.app/:names/:123